set(_CATKIN_CURRENT_PACKAGE "growbot_tlc")
set(growbot_tlc_VERSION "0.0.0")
set(growbot_tlc_MAINTAINER "kilian <meierkilian@gmail.com>")
set(growbot_tlc_PACKAGE_FORMAT "2")
set(growbot_tlc_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(growbot_tlc_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(growbot_tlc_BUILDTOOL_DEPENDS "catkin")
set(growbot_tlc_BUILDTOOL_EXPORT_DEPENDS )
set(growbot_tlc_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(growbot_tlc_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(growbot_tlc_TEST_DEPENDS )
set(growbot_tlc_DOC_DEPENDS )
set(growbot_tlc_URL_WEBSITE "")
set(growbot_tlc_URL_BUGTRACKER "")
set(growbot_tlc_URL_REPOSITORY "")
set(growbot_tlc_DEPRECATED "")